# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 897114cd4c88012a5e79db97c621aadc257a32e1e0224c54f3451769143d0c3c90f71793aea58798c068ee176fd1284cba328a8e97443ba5d456685a1caec398

test:
  secret_key_base: b64505db8f9ed578e84454cb354e1bd7ea04b2cb667f0cd8811a9e21bc08d6554ac196556a9651a32606594234e4d9448147a5ace93ee2a3286cfdef4a29252d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
